---
- include: nrpe.yml
  tags: nrpe

- include: rbl_ip_list_create.yml
  when: rbl_ip_list_create|default(false) == true
  tags: nagios

- include: nagios.yml
  when: nagios_server|default('false') == 'true'
  tags: nagios
