---
- name: Create rbl list | copy script
  copy:
    src: rbl_generate.sh
    dest: /usr/local/bin/rbl_generate.sh
    mode: 0755

- name: Create rbl list | execute script
  command: /usr/local/bin/rbl_generate.sh /tmp/ansible_rbl_list_temporary_file "{{ item.0.normal_check_interval }}" "{{ item.1 }}"
  with_subelements:
    - nagios_rbl_ip_list
    - address
  changed_when: false

- name: Create rbl list | Set owner temporary file
  file:
    dest: /tmp/ansible_rbl_list_temporary_file
    owner: "{{ rbl_ip_list_owner }}"
  changed_when: false

- name: Copy temporary file to destination if different
  shell: "if ! diff /tmp/ansible_rbl_list_temporary_file {{ rbl_ip_list_path }};          
          then                                                                  
              cp -f /tmp/ansible_rbl_list_temporary_file {{ rbl_ip_list_path }} && exit 101 || exit 102;
          else                                                                  
             exit 0;                                                            
          fi"                                                                   
  register: output                                                              
  failed_when: False                                                            
  changed_when: False                                                           
                                                                                
- name: Create rbl list | Command status 1                                             
  debug:                                                                        
    msg: File has been copied                                                   
  changed_when: output.rc == 101                                                
  when: output.rc == 101                                                        
                                                                                
- name: Create rbl list | Command status 2                                             
  debug:                                                                        
    msg: Error copying file                                                     
  changed_when: output.rc == 102                                                
  failed_when: output.rc == 102                                                 
  when: output.rc == 102  

- name: Create rbl list | Remove temporary file
  file:
    dest: /tmp/ansible_rbl_list_temporary_file
    state: absent
  changed_when: false

- name: Create rbl list | set owner
  file:
    dest: "{{ rbl_ip_list_path }}"
    owner: "{{ rbl_ip_list_owner }}"
    group: "{{ rbl_ip_list_owner }}"

- name: Create rbl list | include generated vars
  include_vars: "{{ rbl_ip_list_path }}"
